<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Data processing library for SmartMeter</Description>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CreativeCoders.Net" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
      <PackageReference Include="MQTTnet" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CreativeCoders.SmartMeter.Sml\CreativeCoders.SmartMeter.Sml.csproj" />
    </ItemGroup>

</Project>
