<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Classes for SML protocol implementation to access smart meters</Description>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CreativeCoders.Core" />
      <PackageReference Include="System.IO.Ports" />
      <PackageReference Include="System.Reactive" />
    </ItemGroup>

</Project>
