<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Core library for the SmartMeter server application</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CreativeCoders.Daemon"/>
        <PackageReference Include="Serilog.Extensions.Hosting"/>
        <PackageReference Include="Serilog.Sinks.Console"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CreativeCoders.SmartMessageLanguage\CreativeCoders.SmartMessageLanguage.csproj"/>
        <ProjectReference Include="..\CreativeCoders.SmartMeter.DataProcessing\CreativeCoders.SmartMeter.DataProcessing.csproj"/>
    </ItemGroup>

</Project>
