<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <Description>Daemon for Linux to run the smart meter server</Description>
        <AssemblyName>smartmetersrv</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CreativeCoders.Daemon.Linux" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CreativeCoders.SmartMeter.Server.Core\CreativeCoders.SmartMeter.Server.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="daemon.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="install.sh">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
